### ISSUE TITLE
i still need to make a jira card to be #service-checklist compliant

### ISSUE THREAD

**Issue by vise890** [ovotech/shipit#5]
...and i don't really wanna. Would you be open accepting a PR or something for it?

**Comment by tundsta** [comment]
There's scope for shipit as the source of truth for deployments, and it could publish 'events that have happened' in terms of deployment to kafka. Any views required such as kafka and jira should probably be decoupled from the main service as kafka consumers.

**Comment by cb372** [comment]
@vise890 Sorry about the slow reply, just noticed this. My intention in building shipit was to replace JIRA, as I don't think it's the right tool for the job. My understanding is that JIRA is only mentioned in the service checklist because it was the only tool available at the time, and the checklist can be updated.

**Comment by vise890** [comment]
totally agree, Jira doesn't really seem like a great solution, but I think it would provide quite a smooth migration path if we made the card here.

... people could then just integrate with shipit and rest assured that they're service-checklist compliant, and we can then keep building and eventually deprecate Jira. Thoughts?

**Comment by cb372** [comment]
Fixed by #12
